include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
  
  strong-mode:
    implicit-casts: false
    implicit-dynamic: false
  
  errors:
    missing_required_param: error
    missing_return: error

linter:
  rules:
    # Rendimiento
    - avoid_unnecessary_containers
    - avoid_function_literals_in_foreach_calls
    - prefer_const_constructors
    - prefer_const_declarations
    - prefer_const_literals_to_create_immutables
    - unnecessary_const
    - unnecessary_new
    
    # Tamaño de código
    - prefer_single_quotes
    - unnecessary_this
    - avoid_redundant_argument_values