name: pbstation_frontend
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 0.8.6+1 

environment:
  sdk: ^3.7.2 #flutter 3.29.3

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.3
  intl: ^0.20.2
  web_socket_channel: ^2.4.0
  bitsdojo_window: ^0.1.5
  http: ^1.4.0
  path_provider: ^2.1.5
  flutter_localization: ^0.3.2
  shared_preferences: ^2.5.3
  esc_pos_utils_plus: ^2.0.4
  print_usb: ^0.0.3
  qr_flutter: ^4.1.0
  cupertino_icons: ^1.0.8
  decimal: ^3.2.4
  image: ^4.5.4
  package_info_plus: ^9.0.0
  flutter_launcher_icons: ^0.14.4
  file_picker: ^10.3.3
  dio: ^5.9.0

flutter_launcher_icons:
  windows:
    generate: true
    image_path: "assets/icon/logo.png"
    icon_size: 48 # min:48, max:256, default: 48

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/frames/
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
